// src/SaveStatus.tsx
/**
 * SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
import SaveStatus from './SaveStatus.vue'
import VueWrapper from './VueWrapper'

export default function(props:{saving: Boolean}) {
	return React.createElement(VueWrapper, { componentProps: props, component: SaveStatus })
}

// src/SaveStatus.vue
/**
* SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
* SPDX-License-Identifier: AGPL-3.0-or-later
*/
<template>
	<NcButton type="tertiary" @click="onClick">
		<template #icon>
			<NcSavingIndicatorIcon :saving="saving" />
		</template>
	</NcButton>
</template>

<script>
import { NcButton, NcSavingIndicatorIcon } from '@nextcloud/vue'
export default {
	name: 'SaveStatus',
	components: {
		NcButton,
		NcSavingIndicatorIcon,
	},
	props: {
		saving: {
			type: Boolean,
			default: false,
		},
		onClick: {
			type: Function,
			default: () => { },
		},
	},
}
</script>
